site_name: Lumos Wiki
theme:
  name: material
  palette:
    primary: white
    accent: blue
    
  language: zh
  logo: assets/lumosfans.png
  favicon: assets/lumosfans.png
  icon:
    edit: material/pencil
  features:
    - navigation.instant
    - navigation.tabs
    - content.action.edit
    - toc.follow
    - navigation.top
plugins:
  - search:
      lang: 
        - en
        - zh
      jieba_dict: dict.txt
  - git-revision-date-localized:
      type: iso_datetime

repo_name: ver217/lumos-wiki
repo_url: https://github.com/ver217/lumos-wiki
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2023 Lumos Fans Club

# Nav
nav:
  - 简介:
    - 快速上手: index.md
  - 编年史: chronicle.md
  - Miki:
    - 简介: miki/index.md
  - 小蓝:
    - 简介: aoyi/index.md
  - 十二:
    - 简介: 12/index.md
  - 柠檬汁:
    - 简介: lemon-juice/index.md